version: '3.8'

services:
  app:
    container_name: codespace
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:messaging
    
  messaging:
    container_name: solace
    image: solace/solace-pubsub-standard:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "55555:55555"
      - "8008:8008"
      - "1883:1883"
      - "8000:8000"
      - "5672:5672"
      - "9000:9000"
      - "2222:2222"
    environment:
      username_admin_globalaccesslevel: admin 
      username_admin_password: admin
    # shm_size: '2gb'
