version: '3.8'

services:
  app:
    container_name: solace-dev
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

# override the default network
networks:
  default:
    external:
      name: host